version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: dockerfile/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
  web:
    build:
      context: ./
      dockerfile: dockerfile/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 1002:80